export const contactList = [
    {
      id: 1,
      name: "Munees",
      profilePic: "profile/muneed.jpg",
      lastText: "Thanks Buddy",
      lastTextTime: "12:58 PM",
    },
    {
      id: 2,
      name: "zahin faizal",
      profilePic: "/profile/zahin.jpg",
      lastText: `can i ask a trick question`,
      lastTextTime: "12:45 PM",
    },
    {
      id: 3,
      name: "Nafil Husn M",
      profilePic: "/profile/nafil.jpg",
      lastText: " How was your diet bro?",
      lastTextTime: "12:30 PM",
    },
    {
      id: 4,
      name: "Shameer Bro",
      profilePic: "/profile/shameer.jpg",
      lastText: "No broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 5,
      name: "dad",
      profilePic: "/profile/uppa.jpg",
      lastText: "Hi Dad",
      lastTextTime: "12:00 PM",
    },
  ];
  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "hello",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "What's up?",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Are you free now?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "Yes offcourse",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 7,
      messageType: "TEXT",
      text: "let's go for a movie",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "Ok bro which theatre ?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "Syndicate",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "That's Great",
      senderID: 0,
      addedOn: "12:00 PM",
    },

    {
      id: 6,
      messageType: "TEXT",
      text: "ok I will book the ticket ",
      senderID: 1,
      addedOn: "12:00 PM",
    },

    {
      id: 6,
      messageType: "TEXT",
      text: "Show time 12:00 PM",
      senderID: 1,
      addedOn: "12:00 PM",
    },
   
    {
      id: 6,
      messageType: "TEXT",
      text: "i Have car i will pick you",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "TEXT",
      text: "Thanks Buddy",
      senderID: 1,
      addedOn: "12:00 PM",
    },
  ];
  